.gitignore
BUILDING.md
build.gradle

Updated the build.gradle to support building the MiniClient.jar

Added support for building MiniClient jar in Linux/Window/Mac

---

java/sage/api/Global.java

to allow request properties to be passed to the downloader.
issue #2

Adding overloads to file downloading calls

---

AUTHORS
native/so/HDHomeRun2.0/DTVChannel.cp

just forgot to add myself to Authors and actually removing a TODO as it is done

2 small changes - non functional

---

.gitignore

Just a few more gitignore updates that I noticed in my tree.

More gitignore updates

---

java/sage/CaptureDevice.java
java/sage/PredefinedJEPFunction.java
java/sage/Scheduler.java
java/sage/api/CaptureDeviceAPI.java
java/sage/api/Database.java

1) Added CaptureDevice API support to get & set merit values.
2) Extended the Capture Device comparator to take capture device or capture device input parameters.
3) Added CaptureDevicePriority SortTechnique parameter option to Database's Sort() API call to better sort tuners.

Added additional capture device merit support.

---

build.gradle
build/.gitignore
build/buildtarballs.sh
build/clean.sh

Sage jar is now packaged along with the STV for easier updating of both.

Updated gradle to pull/set the BUILDNUMBER from the git commit count.

---

build/ubuntufiles/server/DEBIAN/config
build/ubuntufiles/server/DEBIAN/control
build/ubuntufiles/server/DEBIAN/postinst
build/ubuntufiles/server/DEBIAN/postrm
build/ubuntufiles/server/DEBIAN/templates

Added debconf features to prompt user for SageTV license key and to create the activkey file when one is provided.

Ubuntu License Key Prompt

---

.gitignore
build.gradle
build/buildall.sh

Should have commited this a few weeks back :)

 fixed the gradle script to build under windows without failing

---

java/sage/MiniClientSageRenderer.java
java/sage/PseudoMenu.java
java/sage/SageRenderer.java
java/sage/Version.java
java/sage/api/Global.java

whereby the client renderer on the server can send hints to the remote client letting it know about which menu or popup is active, and whether or not a keyboard is required.  Also added a new API IsTouchUI that returns TRUE if the remote client is a Touch enabled device.  The Server's Version is updated to 9.0.4 to reflect new APIs and Properties.

Added MENU_HINTS client property

---

native/dll/DShowPlayer-2/PlaybackGraph.cpp

These are the changes Jeff requested be added to the PlaybackGraph to resolve loading MPEG Decoders

DirectShow changes to fix loading of MPEG Decoders

---

java/sage/CaptureDevice.java
java/sage/DShowCaptureDevice.java
java/sage/HDHomeRunCaptureDevice.java
java/sage/IVTVCaptureDevice.java
java/sage/MacNativeCaptureDevice.java
java/sage/MacTrinityCaptureDevice.java
java/sage/NetworkCaptureDevice.java

This one looks correct. Something strange happened when I pushed my changes on the other branch.

Added ability to use a local tuning plugin with a network encoder.

---

java/sage/EncodingServer.java

Fix omitted bufferSize from START command parsing

---

SageTVPluginsDev.md
java/sage/FileDownloader.java
java/sage/plugin/CorePluginManager.java

See the SageTVPluginsDev.md README for information about this change.  If there is still questions, I'll answer them :)

Enable SageTV to load plugins from a SageTVPluginsDev.d directory

---

CHANGELOG.md
java/sage/Version.java

Because of the changes to the plugin system I felt a bump in version was due

Bumped the Version to 9.0.7 so that plugins can use it as a MinVersion

---

.gitignore
java/sage/MediaFile.java
test/java/sage/MediaFileTest.java

Added Test Case to validate the filename creation.

Tweak "extended_filename" to support unicode.

---

java/sage/plugin/CorePluginManager.java
test/java/sage/plugin/CorePluginManagerTest.java

that prevented files from being upgraded correctly.

Fixed severe bug in Plugin Manager

---

CHANGELOG.md
java/sage/Version.java

Updated to Version 9.0.10 (preparing for next release)

---

CHANGELOG.md
java/sage/epg/sd/SDRipper.java
java/sage/epg/sd/json/programs/SDContentRating.java
java/sage/epg/sd/json/programs/SDDescriptions.java
java/sage/epg/sd/json/programs/SDEventDetails.java
java/sage/epg/sd/json/programs/SDMovie.java
java/sage/epg/sd/json/programs/SDPerson.java
java/sage/epg/sd/json/programs/SDProgram.java
java/sage/epg/sd/json/programs/SDRecommendations.java
java/sage/epg/sd/json/programs/Title.java

I also added a few toString() overrides for debugging.

Added teams as people in the SDRipper for favorite scheduling.

---

build/.gitignore
build/copyserverfiles.sh
build/pluginfiles/OriginalV2.plugin.xml
build/pluginfiles/README.md
build/pluginfiles/SageTV3.plugin.xml
build/pluginfiles/build.xml
plugin-uploader.gradle

so they can be installed as a SageTV 9 plugin

Added scripts to package and deploy the legacy SageTV UIs

---

CHANGELOG.md
java/sage/Sage.java
java/sage/Wizard.java
java/sage/api/Global.java
java/sage/api/ShowAPI.java
java/sage/epg/sd/SDErrors.java
java/sage/epg/sd/SDRipper.java
java/sage/epg/sd/SDSession.java
java/sage/epg/sd/SDUtils.java
java/sage/epg/sd/json/programs/SDInProgressSport.java
java/sage/epg/sd/json/programs/SDProgram.java
test/java/sage/epg/sd/SDUtilsTest.java
test/java/sage/epg/sd/json/programs/SDInProgressSportTest.java
test/resources/epg/sd/json/errors/6002.json
test/resources/epg/sd/json/programs/inProgressSportComplete.json
test/resources/epg/sd/json/programs/inProgressSportIncomplete.json

Added New API Methods for In Progress Sport Events.

---

CHANGELOG.md
java/sage/epg/sd/SDRipper.java
java/sage/epg/sd/SDUtils.java
java/sage/nio/BufferedFileChannel.java

I also had a the delayed headshot retrieval re-ordering to prioritize getting headshots for aliases over the normal names, so I fixed that too. That's definitely less of an issue and most people never would have noticed.

Fixed teams not importing since we started importing headshots.

---

installer/wix/SageTVSetup/Bundle.wxs
installer/wix/SageTVSetup/Product.wxs
installer/wix/SageTVSetup/SageTVInclude.wxi
installer/wix/SageTVSetup/SageTVVersionInclude.wxi
native/include/version.h

- ensure the product version is updated correctly during the scripted build process

Fixes for Windows Installer build

---

CHANGELOG.md
java/sage/Carny.java
java/sage/Scheduler.java

This includes the changes suggested here:
https://forums.sagetv.com/forums/showthread.php?p=605158&postcount=14
The changes were confirmed to resolve the issue being described by Tiki.
The other commit is to address a problem with brand new SageTV installs and any other situation whereby SageTV might start without any agents.

Carny not being marked prepped fix.

---

CHANGELOG.md
build/serverfiles/startsagecore
java/sage/Version.java

Let's all agree to leave well enough alone on this one. It's working. We shall not change this piece of code ever again. :)

A missing space in an if test prevents the Linux SageTV start script from running.

---

native/so/FirewireCapture/sage_FirewireCaptureDevice.c

I started cleaning up some of the firewire capture code while trying to get it to work on a new system.

Start cleanup of linux firewire capture code

---

native/so/FirewireTuning/FirewireTuner.c
native/so/FirewireTuning/FirewireTuner.h

Includes a fix for memory leaks on every tune request.
Disabled debug logging until it can be sent through logs.

Cleanup FirewireTuner code

---

native/so/PVR150Tuning/PVR150Tuner.c
native/so/PVR150Tuning/PVR150Tuner.h

Close remote directory file descriptor when loading remotes.

Cleanup PVR150Tuning code

---

CHANGELOG.md
java/sage/Version.java
java/sage/epg/sd/SDRipper.java
java/sage/epg/sd/SDSession.java

I also did the version incrementing and added to the change log what appears to have happened since the last release. If anyone has any concerns about what I have put in the change log, please update it.

Add Schedules Direct lineup by ID.

---

java/sage/BigBrother.java
java/sage/CaptureDeviceInput.java
java/sage/Carny.java
java/sage/Catbert.java
java/sage/DShowCaptureManager.java
java/sage/EPG.java
java/sage/EventRouter.java
java/sage/FastRandomFile.java
java/sage/IOUtils.java
java/sage/Java2DSageRenderer.java
java/sage/PVR350OSDRenderingPlugin.java
java/sage/Sage.java
java/sage/SageConstants.java
java/sage/SageTV.java
java/sage/SageTVConnection.java
java/sage/Scheduler.java
java/sage/Seeker.java
java/sage/UIManager.java
java/sage/UserEvent.java
java/sage/VideoFrame.java
java/sage/WindowsServiceControl.java
java/sage/Wizard.java
java/sage/api/Global.java
java/sage/api/WidgetAPI.java
java/tv/sage/mod/Module.java
java/tv/sage/mod/STVReader.java

Part of SageConstants cleanup.  Removed LITE usage.

Removed LITE

---

java/sage/Airing.java
java/sage/FSManager.java
java/sage/MediaFile.java
java/sage/MetaImage.java
java/sage/SageConstants.java
java/sage/SageTV.java
java/sage/Seeker.java
java/sage/SeriesInfo.java
java/sage/Show.java
java/sage/VideoFrame.java
java/sage/Wizard.java
java/sage/api/Configuration.java
java/sage/api/Global.java

Last of the SageConstants flags

Removed PVR flag

---

java/sage/Airing.java
java/sage/MediaFile.java
java/sage/Sage.java
java/sage/SageTVConnection.java
java/sage/Show.java
java/sage/Wizard.java

As per Jeff's suggestion, removed the COMPACT_DB flag.

Removed COMPACT_DB flag

---

CHANGELOG.md
native/ax/Channel-2/Channel.c
native/ax/Native2.0/NativeCore/ATSCPSIParser.c

Fix for scanning issues discussed in issue #338

Fix: ATSC Scanning Blank and Garbled Numbers

---

AUTHORS
CHANGELOG.md
java/sage/Version.java
stvs/SageTV7/OnlineVideos/OnlineVideoLinks.properties
stvs/SageTV7/OnlineVideos/OnlineVideoUIText.properties

See change log for full list of STV changes.

Fixed some minor bugs/issues in the STV and removed unused items.

---

CHANGELOG.md
build/builddll.sh
installer/wix/SageTVSetup/PreBuild.bat
installer/wix/SageTVSetup/Resource/SageTVTheme.wxl
installer/wix/SageTVSetup/Resource/SageTVTheme.xml
installer/wix/SageTVSetup/SageTVVersionInclude.wxi
native/include/version.h
third_party/SageTV-LGPL/imageload/Makefile.win
third_party/SageTV-LGPL/imageload/swscale.c

changes included to build imageLoader and swscale dll's on windows

Updates for 9.1.7 including changelog [ci release]

---

CHANGELOG.md
installer/Readme.md
installer/wix/SageTVSetup/InstallerBuild.ps1
installer/wix/SageTVSetup/SageTVVersionInclude.wxi
installer/wix/SageTVSetup/runGradle.bat
java/sage/Version.java
native/include/version.h

- includes the powershell script used for building windows native code and the installer

Release of version 9.1.8 for windows

---

CONTRIBUTORS
java/sage/api/Database.java

https://github.com/google/sagetv/issues/389

Fix Issue #389, SortByOrigAiringDate violating its general contract

---

build/ubuntufiles/client/DEBIAN/control
build/ubuntufiles/server/DEBIAN/control

Resolves Issue #393 
I tested by installing.  installation was successful and installed net-tools.

Update deb dependencies

---

CHANGELOG.md
java/sage/DShowMediaPlayer.java

- STV updated - version, system info to display bitness, whitelist LAV Audio and Video Decoders
- DShowMediaPlayer - updated to whitelist LAV Audio and Video Decoders

Updates to whitelist LAV Filters and display bitness in system information

---

CHANGELOG.md
build.gradle
installer/wix/SageTVSetup/Bundle.wxs
installer/wix/SageTVSetup/Directx9.wxs
installer/wix/SageTVSetup/InstallerBuild.ps1
installer/wix/SageTVSetup/PreBuild.bat
installer/wix/SageTVSetup/Product.wxs
installer/wix/SageTVSetup/Resource/SageTVTheme.wxl
installer/wix/SageTVSetup/Resource/SageTVTheme.xml
installer/wix/SageTVSetup/SageTVInclude.wxi
installer/wix/SageTVSetup/SageTVSetupBootstrapper.wixproj
installer/wix/SageTVSetup/SageTVSetupMSI.wixproj
installer/wix/SageTVSetup/SageTVVersionInclude.wxi
installer/wix/SageTVSetup/ac3filterinstaller.wxs
installer/wix/SageTVSetup/java7installer.wxs
installer/wix/SageTVSetup/vsruntime10installer.wxs
installer/wix/SageTVSetup/vsruntime14installer.wxs
java/sage/Version.java
native/include/version.h

- Windows installer changes
- minor build.gradle change to build sage.jar on windows
- skipped 9.2.0 as many users are using that beta release and moving to 9.2.1 will allow them to upgrade

Build for 9.2.1 [ci release] - first release of Windows x64 installers

---

CHANGELOG.md
native/dll/DShowCapture-2/DShowCapture.h
native/dll/DShowCapture-2/GraphManager.cpp

HVR-5525 has 3 BDA tuners
Probably won't be any new tuners with more than 3 tuners, but cater for 4 to avoid rework

Change maximum number of BDA tuners from 2 to 4

---

CHANGELOG.md
java/sage/BigBrother.java

Allow the 5 and 10 minute watch ignore times to be altered via properties.  Defaults are from the original constants.
Forum discussion here:  https://forums.sagetv.com/forums/showthread.php?t=66005

Change watch ignore times from constants to properties.

---

.gitignore
native/ax/StrmDeMux/CPushReader.cpp

Revert changes to CPushReader.cpp

---

CHANGELOG.md
native/exe/ServiceControlLaunch/ServiceControlLaunch.cpp
native/exe/ServiceControlLaunch/StdAfx.h

Support local SageTV folder JRE
Tidy up warnings in VS2015 by changing to MS "safe" APIs
Add ReleaseStringUTFChars to release allocated memory
Change JAVA version in popup messages
Remove disable warnings pragma

Change service launcher (Windows) to support local JRE

---

native/common/jni-util.cpp
native/common/uniapi.cpp
native/dll/DX93D/SageTVDX93D.cpp
native/dll/DX93D/StdAfx.h
native/dll/Win32DLL/OpenGLVideoRenderer.cpp
native/dll/Win32DLL/SageTVWin32DLL.cpp
native/dll/Win32DLL/SageTVWin32DLL.def
native/dll/Win32DLL/StdAfx.h
native/dll/Win32DLL/WMATagParser.cpp
native/dll/Win32DLL/WindowsServiceControl.cpp
native/dll/WinRawInput/WinRawInput.def
native/exe/MiniClientLauncher/MiniClientLauncher.cpp
native/exe/ServiceControlLaunch/ServiceControlLaunch.cpp
native/include/jni-util.h
third_party/Microsoft/BaseClasses/wxutil.cpp

Changes from SageService Launcher applied to MiniClient Launcher
Resolve Compile and Static Analysis warnings
Change to MS safe/secure functions

Clean up of VS2015 warnings - Part 3

---

CHANGELOG.md
java/sage/media/format/FormatParser.java
java/sage/media/format/FormatParserPlugin.java
java/sage/media/format/MediaFormat.java
java/sage/media/format/VideoFormat.java

Added the ability to use a Plugin for format detection of media files instead of built in ffmpeg.
Added 2160p as a Pretty resolution to VideoFormat
Added HEVC as a supported media format

Added the ability to create a Format parser plugin

---

.gitignore
CHANGELOG.md
java/sage/MediaFile.java
java/sage/VideoFrame.java
java/sage/api/MediaFileAPI.java
java/sage/media/format/ContainerFormat.java
java/sage/media/format/SubpictureFormat.java

Added forced property to the subtitle tracks.  Added code to auto select forced subtitle tracks that match the default audio language.  Added the forced subtitle property to output in the API.
Also added netbeans project files to the .gitignore files.

Add forced subtitle property to media file

---

CHANGELOG.md
installer/wix/SageTVSetup/InstallerBuild.ps1
installer/wix/SageTVSetup/SageTVVersionInclude.wxi
installer/wix/SageTVSetup/java8installer.wxs
installer/wix/SageTVSetup/lavfiltersinstaller.wxs
java/sage/Version.java
native/include/version.h

Updates to Windows installer and changelog for version 9.2.2

Release for version 9.2.2 [ci release]

---

native/ax/Channel-2/Channel.h

These just look wrong and have caused various problems, if they break anything they can be put back.

Fix bool defs in Channel.h

---

.github/workflows/ci.yml
build/build3rdparty.sh
build/buildmplayer.sh
third_party/mplayer/libavcodec/amrwb_float/enc_if.c
third_party/mplayer/libavcodec/cabac.h
third_party/mplayer/libavcodec/h264.c
third_party/mplayer/vidix/cyberblade_vid.c
third_party/mplayer/vidix/mach64_vid.c
third_party/mplayer/vidix/nvidia_vid.c
third_party/mplayer/vidix/pm3_vid.c
third_party/mplayer/vidix/savage_vid.c
third_party/mplayer/vidix/unichrome_vid.c

I named this file wrong, fix that. Also I need to see if it works with a newer version of Ubuntu. GitHub Actions is deprecating 16.04 this month.

Rename file and update Ubuntu version for CI

---

.github/workflows/ci.yml
build/deploy.sh
installer/wix/SageTVSetup/SageTVVersionInclude.wxi
native/include/version.h

This also should fix the deploy operation in CI

Release for version 9.2.6 [ci release]

---

build/deploy.sh

This should fix deploy so it runs on push requests now (second try).

Release for version 9.2.6 (try 2) [ci release]

---

.github/workflows/ci.yml
CHANGELOG.md
build.gradle
gradle/wrapper/gradle-wrapper.properties
java/sage/Version.java

Resolves issue https://github.com/google/sagetv/issues/468
Still requires changes to the github workflow for automatically building linux bilds

Changes to support a linux build to run on Java 8
