AUTHORS, CONTRIBUTORS, java/sage/FileDownloader.java
Added the ability for sage to set a default user-agent string of "SageTV/x.x.x" for file downloads.  Will only set the new string when property "use_sagetv_user_agent" is set to true, otherwise it will remain the default "Java/x.x.x_xx".
PULL REQUEST NOTE:  This is a partial, yet standalone fix for Issue #2.
=> Added ability for sage specific user-agent

.gitignore
After the linux build git shows 1900+ untracked files. This commit
adds a top level .gitignore file to address the low hanging fruits
first. It shrinks the untracked files down to about 270.
The remaining ones are in third_party/ and would need more selective
pruning.
Tested by searching for specified pattern in a clean sagetv repo and
no files were found.
=> add initial .gitignore

java/sage/Carny.java, java/sage/EPG.java, java/sage/FSManager.java, java/sage/MMC.java, java/sage/Ministry.java, java/sage/NewStorageDeviceDetector.java, java/sage/Scheduler.java, java/sage/Seeker.java, java/sage/ServerPowerManagement.java, java/sage/Wizard.java
I believe I found all of the Singletons that needed tweaking.  Let me know if I missed any.
=> Update Singleton creation pattern to be thread safe

java/sage/FileDownloader.java
Used primarily for testing, but can be used to enable connections with otherwise locked out sources (like HD PlayOn captures).
=> Added property 'custom_user_agent' to override default.

AUTHORS, CONTRIBUTORS, build/buildubuntu.sh, build/ubuntufiles/client/DEBIAN/control, build/ubuntufiles/client/usr/share/applications/sagetv.desktop, build/ubuntufiles/server/DEBIAN/control
* Put the correct architecture in the .deb filename
* Put version and architecture into .deb control files at build-time
* Put version and architecture into the sagetv.desktop file at build-time
* Change the .deb Java dependency from Sun's v6 JRE, to any JDK or JRE v5 or higher (I think I saw in the forums that the minimum is 5)
=> Fixes for hard-coded values and Java dependencies in the Ubuntu build.

native/ax/Native2.0/NativeCore/TSCRC32.c
Changed crc from unsigned long to uint32_t to fix crash on 64-bit systems.
=> Fix for 64-bit scan crash

java/sage/WarlockRipper.java
Whitespace characters were not being stripped when reading activkey file resulting in an inability to connect to EPG server.
=> Trim string created from reading activkey file

native/so/DVBCapture2.0/Makefile
Also clean up unnecessary dependencies.
Here are the linker errors this fixes:
gcc   -Wall -o dvbtest dvbtest.o libNativeCore.so  ../../lib/NativeCore/channel.a
dvbtest.o: In function `Java_sage_DVBCaptureDevice_createEncoder0':
/files/sagetv-master/native/so/DVBCapture2.0/sage_DVBCaptureDevice.c:331: undefined reference to `createCircBuffer'
/files/sagetv-master/native/so/DVBCapture2.0/sage_DVBCaptureDevice.c:343: undefined reference to `ACL_CreateMutex'
dvbtest.o: In function `Java_sage_DVBCaptureDevice_setupEncoding0':
/files/sagetv-master/native/so/DVBCapture2.0/sage_DVBCaptureDevice.c:610: undefined reference to `resetCircBuffer'
/files/sagetv-master/native/so/DVBCapture2.0/sage_DVBCaptureDevice.c:611: undefined reference to `ACL_CreateThread'
dvbtest.o: In function …
=> Fix linker error for dvbtest

AUTHORS, CONTRIBUTORS, java/sage/MMC.java
Added an overload to redetectCaptureDevices to only detect devices on one CaptureDeviceManager.  These changes were discussed in issue "Want to be able to load a Network Encoder as a runnable class"
=> Add overload to redetectCaptureDevices

java/sage/EPG.java
EPG thread only logs the Throwable.toString() when it catches an
exception from an EPG plugin, which isn't very helpful when tracking
down bugs.  A full stacktrace makes solving problems rather easy.
=> Log full stacktrace on EPG plugin errors

AUTHORS, CONTRIBUTORS, java/sage/Agent.java, java/sage/Carny.java, java/sage/api/FavoriteAPI.java
* Add a flag to favorites (Agent) that allows for them to be disabled.  
* Add the logic in Carny to test that flag.  
* Add API methods to query and set that flag.
Note: The Agent flag is whether or not the Agent is DISabled, because that allows the default state of the flag (0) to mean ENabled (i.e. disabled is false).  The API methods test and set whether the favorite is ENabled (which is the opposite of the Agent flag) because I thought that made more sense for a user of the API.
I'll be submitting a separate pull request with an STV update to expose this new functionality once this pull request is accepted..  I've tested with a locally modified v7 STV.  I just need to get those changes made to the latest STV from github.
=> Allow for favorites to be disabled

install/config/PredefinedDVBC.frq
added a few new frequencies (mainly for cablecom provider) and sorted the list.
Small update to cope with new frequencies in my country / provider.
=> Updated DVB-C frequencies for Switerland

java/sage/MediaFile.java
Keep all legal filename characters in show and episode names. Added spaces around '-' delimiters in name string to allow 3rd party metadata scrapers to read SageTV recordings.
=> Allow all valid characters in filename

java/sage/NetworkCaptureDevice.java
If a network encoder is configured and not found, it was previously ignored, unless the user navigated to the source details page, which would trigger an IsFunctioning() call.  It will now be checked for every 15 seconds, and if it starts responding, will be enabled and the scheduler kicked off.  This capability was created for the embedded platform (checking every second), but was never implemented in the standard server.
=> Monitor lost/offline network encoders

gradle/wrapper/gradle-wrapper.properties, java/sage/plugin/CorePluginManager.java
This is largely so that we can publish specific V9 version of legacy plugins, like, sagex-apis, Gemstone, Phoenix, etc, without having an impact on SageTV V7 installations.
See the following thread for more details.
http://forums.sagetv.com/forums/showthread.php?p=582228
=> Updated the Core Plugin Manager to support a specific V9 Plugin Repo URL and added support for custom repos

native/ax/Native2.0/NativeCore/ATSCPSIParser.c, native/ax/Native2.0/NativeCore/PSIParser.c, native/exe/SageLauncher/SageLauncher.rc
This behavior is observed when using Hauppauge HVR 1250, 1600, 1800 & 2250 tuners, although it likely occurs with any BDA (internal, non-network) tuner.  A non-Sage channel scan (TV, HDHR, or  Hauppauge WinTv app, or TsReader) confirms that the correct channel info is present in the data stream.  The issue was introduced in Sage7 and didn't occur with Sage6.  Possibly related to another old issue; see comment in ChannelScan.c re: 'QAM stream carries DVB-C PSI in Lubbock TX'.  
Suddenlink cable (clear QAM, in Truckee, Calif) carries some ATSC streams with a 12:1 ratio of DVB to ATSC packets.  This mixture of packets (which arrive in no particular order) caused the channel scanner to get confused.  Depending upon when it started looking at the pkt stream, stream_format might get set to …
=> Fix: QAM channel scan is unreliable; often reports many channels as DTV-x-y

native/exe/MiniClientLauncher/MiniClientLauncher.rc, native/exe/SageLauncher/SageLauncher.rc, native/exe/SageLauncher/SageLauncher.vcxproj, native/exe/ServiceControlLaunch/ServiceControlLaunch.vcxproj
Manifests now force Administrator properly.  Version numbers set to 9.0.4.220 as well.
=> Manifests and version changes for launchers for Client, Server and ServiceControl

java/sage/UIManager.java
As per [discussion on the forums](http://forums.sagetv.com/forums/showthread.php?p=584289&postcount=246) 
Changed this property's default value (wizard/revert_stv_on_upgrade) to false so upgrades do not force the STV to be changed from a custom one to the default one.  Users can still change the value of this property (wizard/revert_stv_on_upgrade) to true if they are having any issues with an STV that won't launch
=> Default wizard/revert_stv_on_upgrade to false if it is not already set

native/crosslibs/Freetype/Makefile.win, native/crosslibs/Freetype/sage_FreetypeFont.c, native/crosslibs/Freetype/sage_FreetypeFont.h
This request fixes the Freetype font errors when making JNI calls to the native library on Linux:
`Tue 2/2 0:26:10.529 [MiniUIServerConnection@1decba4d] Error loading Freetype Font; trying to load Java font instead; error=java.lang.UnsatisfiedLinkError: sage.FreetypeFont.loadFreetypeLib0()J`
The function names were originally prefixed/hard-coded with an underscore to make them work in the Windows JVM but this caused the calls to fail in Linux. The solution is to remove the underscores which fixes the Linux issue, and then add the "-Wl,--kill-at" linker option for Windows MinGW so the DLL exports the undecorated symbol names.
After doing some research, I learned that the Windows JVM JNI call will try two methods when calling a native function: _functionName@x and functionName, but the …
=> Fix Freetype font UnsatisfiedLinkError in Linux and cleanup/fix Windows MinGW DLL build

CONTRIBUTORS, native/exe/SageLauncher/SageLauncher.vcxproj
The installer is now taking a different approach for the registry permissions and no longer needs this elevation.
Added myself into CONTRIBUTORS
=> Manifest changes to remove the need for elevation from server/client/service

native/crosslibs/Freetype/sage_FreetypeFont.c
Starting with FreeType 2.4, the new Bytecode Interpreter renders many of the commonly used UI fonts slightly smaller than the older versions.  This issue is noticeable when comparing a Windows SageTV UI to a Linux SageTV UI (at least on an extender), because most Linux distributions since 2010/2011 have FT 2.4 or higher but the FreeType used to build the SageTV static FreetypeFontJNI.dll appears to be 2.1.10.
This fix changes the rendering so that SageTV generates the same font sizes with the newer FT versions as it did with the older FT version that is used in the V7/V9 Windows distribution, resulting in the same UI "look" on both platforms.  This will also prevent the font sizes from being reduced if the Windows FreetypeFontJNI.dll is rebuilt in the future using a newer FreeType.
I …
=> FreeType fonts rendering to a smaller size with FT 2.4.0 and higher

native/ax/Channel-2/Channel.c, native/so/DVBCapture2.0/DVBCaptureDevice.h, native/so/DVBCapture2.0/sage_DVBCaptureDevice.c
Use non-legacy v4l-dvb API for tuning DVB-S2/PSK_8
Fix crash when scanning DVB-S channels
=> Use non-legacy v4l-dvb API for tuning DVB-S2/PSK_8

java/sage/Ministry.java, java/sage/NetworkEncoderManager.java, java/sage/ServerPowerManagement.java
Added a function requiresPower() to Ministry, and added a check to ServerPowerManagement to check it.  This functionality clones how ServerPowerManagement checks Seeker for activity.
=> Allow Ministry (Transcoding queue) to keep Server awake.

java/sage/MediaServerRemuxer.java
I missed this one since my test cases actually passed without this modification, but just the other day I caught a few transition that timed out because over 8MB of data was processed without finding a transition point. The root of the problem is signed bytes. This masks the bytes so we are comparing the correct "unsigned" value.
=> The transition (SWITCH) point for MPEG2-PS would sometimes never be found because of signed bytes in Java.

test/java/sage/IOUtilsTest.java
The problem is the line separator in Linux and Windows are different.
=> IOUtils test fails on Windows.

java/sage/MediaFile.java
Change the logic to determine valid characters in extended filenames to
a whitelist. Unicode characters in filenames were causing file system
errors in Linux.
=> Change extended filenames logic

test/java/sage/MediaFileTest.java
The test isn't working on Windows. ’Test99: Namé’ is being turned into ’Test99: NamÃ©’ by the compiler. I looked up the UTF-8  code for this the character é and it's 0xC3A9 which explains how one character somehow became two (even though that should fit within a character; maybe a bug in Java too). Oddly enough in UTF-16, it's 0x00E9, so I change é to \u00E9 and now the test is passing.
=> ’Test99: Namé’ is becoming ’Test99: NamÃ©’ on Windows.

java/sage/WarlockRipper.java
This is a real problem for people using XMLTV plugins because they keep getting error messages and the guide data is not being imported. Not surprisingly, this does not prevent the plugin itself from loading, but since we check for the license key before we try to use the plugin, it fails immediately.
=> Fixed bug in the EPG license detection logic. We now also check for NOKEY.

CHANGELOG.md, java/sage/Version.java, java/sage/epg/sd/SDImages.java, java/sage/epg/sd/SDRipper.java, java/sage/epg/sd/SDSageSession.java, test/java/sage/epg/sd/SDImagesTest.java, test/java/sage/epg/sd/json/images/SDProgramImagesDeserializerTest.java, test/resources/epg/sd/json/images/programImagesShow.json
When you have two (or more) servers competing for a token from Schedules Direct (you can only have one per account), they could end up mostly in sync with their request frequencies, so I added to the two methods used most when downloading guide data to wait a random timeout when the token unexpectedly expires before getting a new one.
This also cleans up some image processing assumptions that have proven to be less than reliable. After pouring over a lot of data that the kinds of images we are looking for to place in Show objects only appear in programs that are movies, so now we don't even try to get any images if the program is a series since the images will not be specific to that episode and the one image that will be is tall instead of wide which makes it awkward and somewhat …
=> Schedules Direct fixes and updates.

build/serverfiles/startsagecore
Added $(if [[ $EUID -eq 0 ]]; then echo '-XX:ThreadPriorityPolicy=1'; fi) so that when SageTV is started by non-root users it will not throw an error due to lack of permissions.
=> Check for root to enable ThreadPriorityPolicy

java/sage/LinuxUtils.java, test/java/sage/LinuxUtilsTest.java
When the IP address can't be determined (ie, not using eth0 or eth1) you get a NPE.   This fixes the NPE, but also adds ent1 br0 and docker0 to the list of devices to check for IP address.  The code will iterate all those devices looking for the first one that returns an address.
=> Fixes a NPE that happens in some coditions

java/sage/Version.java, java/sage/plugin/PluginEventManager.java, test/java/sage/plugin/PluginEventManagerTest.java
If the Plugin Manager experienced and error (ie, passed in null map), then the event that was being processed would never get cleaned up, and the queue would always look like it is busy.  This fix ensures that the queue gets cleaned up, and, that you can pass a null map.
=> Fixes deadlock in the Plugin Manager

CHANGELOG.md, java/sage/Ministry.java
As per #146, should now only look for queued and in progress jobs to prevent sleep.  Previously, any job in the list, including failed and completed jobs, were preventing sleep.
=> Fixed so that Ministry will not allow sleep while converting.

build.gradle, java/sage/FSManager.java, java/sage/Sage.java
This allows a non-root instance of sagetv to import a dvd iso (previously it would fail).   I'm unsure if there are other changes that would be required in order to actually play the dvd... but these changes do allow it to be imported.
There are many places in SageTV where "mount" is used... I'm thinking that a better long term solution might be to create a "Mount" class that manages the need for sudo, and then we find/replace all the exec "mount" (and "umount") places with a Mount class than can manage this.
=> Fix to allow mounting DVD iso images as non-root

CHANGELOG.md, java/sage/epg/sd/SDRipper.java
An issue recently came up in the forums that revealed that it was possible to have more than one lineup have the exact same name. This code adds the unique code associated with every lineup if there is a duplicate within the returned lineups.
Also recently it appears that at least Canada is using additional characters in the provided regex, so things were changed to remove the starting / and the last / as long as at least one character is in between them. That formatting works fine for JavaScript, but not for Java. Also, so that this is less of a burden on users in the future, if the regex isn't formatted in an expected way, it will just say that it passed. This feature is really just to make users more aware of when they make a mistake and doesn't really serve a greater purpose.
=> Fixed parsing of regex for postal codes and added duplicate lineup name support.

CHANGELOG.md, java/sage/epg/sd/SDUtils.java, test/java/sage/epg/sd/SDUtilsTest.java
This is needed because radio stations would otherwise have the exact same channel numbers as normal channels.
=> Retain prepended zeros if the channel  number is 4 digits (including the zeros).

installer/wix/SageTVSetup/PreBuild.bat
These are now to be installed in the JARs folder so plugin preview of websites works in windows.
=> Windows Installer fix for jdic.jar and packager.jar 

java/sage/Wizard.java, java/sage/epg/sd/SDRipper.java, java/sage/epg/sd/json/programs/SDDescriptions.java
It turns out that sometimes some airings actually do end up being found using the method we added to the Wizard and this prevents the station from being invalidated and re-downloaded. I changed it to just check for an airing at this exact time and if it doesn't exist or is a No Data airing, we invalidate the station. This is also based more strongly on data we need now instead of data we have now.
I also added some methods I added for Seeker2 to create timed/manual recordings because I really didn't like the idea of creating an airing outside of the Wizard within Seeker. It just feels like the wrong place to do this. I'm not ready to commit the Seeker2 core changes yet since I'm still slowly working out a few small, but known issues.
=> Some Schedules Direct missing station improvements.

java/sage/Agent.java, java/sage/Version.java, java/sage/api/FavoriteAPI.java
Creates a new API, GetPotentialFavoriteAirings, that works exactly the same as GetFavoriteAirings, except that it returns the airings as if the airing were enabled, even if the favorite is disabled.
This will be used in an update to the STV to show upcoming airings for a favorite even when it is disabled.  (Issue #154)
=> Create new API, GetPotentialFavoriteAirings

build/build3rdparty.sh
Build libx264 on Linux with -fno-aggressive-loop-optimizations when
using GCC 4.8 or newer.
Fixes issue 215.
=> Avoid crash in x264_cqm_init().

build/buildso.sh
This fixes a compile time error, caused by hwaccels in ffmpeg being dependant on h264 encoders. Since hwaccels aren't being used, they should be turned off along with all the other unused parts anyway.
=> Disable hwaccels in libMpeg2Transcoder/ffmpeg

CHANGELOG.md
The default is still 14 days.
I also fixed capitalization in new SD logo option. This was a small oversight that I missed because of my screen resolution when I was editing the STV. :)
I added a note for all developers on how to correctly increment versions after releases. We can build on this so that everyone is always on the same page on what incrementing to a new version actually entails. I have been guilty of missing steps here too, so I thought it would be nice to have this information somewhere very easy to find for everyone.
=> Increased possible range for scheduling lookahead to 21 days in the UI.

build/serverfiles/startsagecore
Double end brackets need a space in front.
=> Fix bash syntax error in startsagecore.

.travis.yml, build/deploy.sh
Will read the last git commit message and if that message contains `[ci release]` then this script will push to Bintray as a release, tagging the release with the `VERSION` tag.
eg, if the message was `"Updated release version [ci release]"` then this script will push the release to Bintray `AFTER` a successful build that is `NOT` a pull request.
It will then `git tag` the release with the `VERSION` tag and then `push` that tag to github.
Secure Environment Requirements
`BINTRAY_USER`  : For releasing
`BINTRAY_API`   : For releasing
`GITHUB_KEY`    : For tagging (if empty then tagging will not be done)
`GITHUB_USER`  : For tagging
`GITHUB_EMAIL`  : For tagging
`NOTE`: Travis has not been updated, yet, to know about the secure variables.  If we agree this is something we want, I can update …
=> added deploy script for auto-deployment to Bintray and github release tagging

CHANGELOG.md, java/sage/media/sub/MP4TextSubtitleHandler.java, java/sage/media/sub/VobSubSubtitleHandler.java
=> VOB and MP4 subtitles locking methods were not being called.

CHANGELOG.md, java/sage/Person.java, java/sage/epg/sd/SDRipper.java
I reduced the thread count to 4 for importing person images because computers with slower connections don't appear to be able to keep up with 16 simultaneous connections which appears to have lead to threads terminating early in the thread executor (the queue is empty and 5 seconds have passed), leading to excessive thread creation.
I added additional logging in the key areas that would provide us with some insight if this kind of situation is still a problem for the affected users after upgrading.
=> Schedules Direct person import improvements.

java/sage/epg/sd/SDRipper.java
It turns out we have some users with even slower internet access than I ever expected and the threads are still idling long enough they stop and later get restarted. Now we just start all of the needed threads and leave them running until the executor is shutdown and the queue is empty.
=> Added more exception handling and made the thread executor always start 3 threads and keep them running.

CHANGELOG.md, native/dll/DShowCapture-2/DShowUtilities.cpp, native/dll/DShowCapture-2/DeviceDiscovery.cpp, native/dll/DShowCapture-2/DeviceVerify.cpp, native/dll/DShowCapture-2/Encoder.cpp
The Hauppauge WinTV-dualHD usb stick is a dual-tuner device.  Hauppauge's BDA driver registers only a single Receiver Component ('TS Capture') for it's 2 Source Filters (ATSC Tuner, ATSC Tuner 2).  Historically, this caused Sage to present only a single Video Capture device to the user ('Hauppauge WinTV-dualHD TS Capture').
This fix makes both tuners usable under Windows.
As a side effect, any user who had previously used & configured the dualHD device (as '...TS Capture') will need to Add and configure the 2 tuners ('...ATSC Tuner' and '...ATSC Tuner 2').  This is necessary because of the way Hauppauge's BDA driver presents the internal devices.
The fix has also been verified by Forum user (and Moderator) SHS.
=> Fix: Added support for 2nd tuner of Hauppauge WinTV-dualHD usb stick (Windows)

CHANGELOG.md, installer/wix/SageTVSetup/sagetvregistry.wxs, java/sage/CaptureDeviceInput.java, native/dll/DShowCapture-2/Crossbar.cpp, native/dll/DShowCapture-2/DeviceVerify.cpp, native/include/sage_DShowCaptureDevice.h
* HD-PVR2 video capture device: add ability to select multiple audio inputs (Windows)
* HD PVR 60 video capture device: new device support (Windows)
Beta tested by Sage forum user (& moderator) SHS
Regression tested with Hauppauge capture devices: HD-PVR, HD-PRV2, Colossus
=> HD-PVR2 & HD PVR 60 capture device support (Windows)

java/sage/Show.java, java/sage/Wizard.java
When a show desc or episdode name is longer than 32KB the import will fail due to reading old byte arrays and their lengths as shorts.  Remove the byte arrays in favor of just using strings so the application doesn't crash.
=> Fix long desc / episode name crash 

java/sage/Wizard.java
This addresses issue #383 where NULL people were added to SeriesInfo, which in turn caused exceptions when accessed later.  User graywolf has been running a jar with this modified code for the past 3 weeks with good results, including a debug log event showing a caught NULL.  I recompiled and tested the jar fresh from this PR commit this evening.
I left the debug log statement in there because it should be rare and can help identify the source of these NULLs.  In this case, I believe BMT may be providing the seriesinfo data.
=> Block NULL people/characters in addSeriesInfo.

.gitignore, CHANGELOG.md, native/dll/DShowCapture-2/CAMCtrl.cpp, native/dll/DShowCapture-2/Crossbar.cpp, native/dll/DShowCapture-2/DeviceDiscovery.cpp, native/dll/DShowCapture-2/DeviceVerify.cpp, native/dll/DShowCapture-2/SageDTV.cpp, native/dll/DShowCapture-2/ScanChannel.cpp, native/dll/DShowCapture-2/TunerPlugin.cpp, native/dll/Win32DLL/SageTVWin32DLL.cpp
Hauppauge HVR-4400 and other 885 hybrid variants contain Hauppauge Alt TS Capture for DVB-S/S2 and Hauppauge TS Capture for DVB-T/T2
This change allows selecting the Hauppauge 885 Alt TS Capture device to add the DVB-S/S2 tuner
and allows selecting the Hauppauge 885 Video Capture device to add the DVB-T/T2 tuner
Fix typos while doing code review
=> Add support for HVR-4400 and other 885 variants (Windows)

CHANGELOG.md, native/dll/DShowCapture-2/FilterGraphTools.cpp
This issue was discovered during beta testing of Sage-x64 Windows installer v1.103.
Sage-x64 can encounter thread-hangs when Ceton InfiniTV or HdHomeRun Prime CableCARD tuners are currently installed or have previously been installed in the computer.  HDHR (ClearQAM) tuners don't encounter the problem.
Symptoms:
1) Disk Space Bar in the GUI takes several minutes to update after Sage initially starts up.  A test system with one HDHR Prime and one Ceton InfiniTv took nearly 25 minutes for the Disk Space Bar to update.
2) System Messages may log "Recording Missed Due to Capture Device Failure" at the beginning of a recording, but the recording eventally does start after approx. 30 seconds (or more).
3) Inspection of SageTv_0.txt log reveals thread hangs (usually MainMsg) for nearly 30 …
=> Fix: Sage-x64 hang due to CableCARD tuners (Windows)

native/dll/DShowPlayer-2/DVDPlaybackExtensions.cpp
Due to an improper data type for the params passed into GetEvent(), DVD menus wouldn't work on Windows 64-bit version.  I added (int, UNLONG and DWORD) casts to suppress compiler warnings.  The fix has been confirmed by me and another user.
=> Fix 64-bit DVD menu.

native/dll/DShowPlayer-2/MusicVisualizer.cpp, native/dll/Win32DLL/SageTVWin32DLL.cpp, third_party/Microsoft/FileSource/AsyncIO.cpp, third_party/Microsoft/FileSource/AsyncIO.h
This fixes 2 more 64-bit Windows issues:  1. The music visualizer would crash when started.  2. AVI playback would crash on some systems.  The music fix needed a 64-bit specific DLL function call plus a struct 'pack' pragma to align with the Java DLL's expectation.  I added the same 'pack' to the other place we use the same struct even though it was already defaulting to the right size, in case a future code change affects that default.  The AVI fix was in the File Source filter where downstream filter context reference needed to be a DWORD_PTR instead of a DWORD.  Tested by me and 2 other users.
=> Fix Windows 64-bit music visualizer and AVI playback crashes.

CHANGELOG.md, install/config/PredefinedDVBS.frq
Updates for OPTUS D1 transponder changes to DVB-S2
=> Updates for OPTUS D1 transponder changes to DVB-S2

native/exe/SageLauncher/launcher.cpp
This fixes a 64-bit automatic service startup issue discussed here:  https://forums.sagetv.com/forums/showthread.php?t=66069
Also increased the heap to 1G for 64-bit installs since that's a major reason for switching to the 64-bit version.
=> Fix 64-bit Windows service launcher.  Set default heap to 1G for 64-bit.

.travis.yml, CHANGELOG.md, java/sage/DirecTVSerialControl.java, native/dll/DirecTVSerialControl/DirecTVSerialControl.cpp, native/include/sage_DirecTVSerialControl.h
64-bit changes broke DirecTVSerialControl (handle size mismatches).  Forum thread here:  https://forums.sagetv.com/forums/showthread.php?t=66130  Confirmed fixed by 2 users.
Also updated the changelog to include the previous Windows service launcher fix.
=> Fix DirecTVSerialControl not working in 9.2

CHANGELOG.md, java/sage/epg/sd/json/map/channel/SDAdvancedChannelMap.java
This fixes a rare issue that currently only plagues one user. Basically the integer from Schedules Direct is an unsigned integer, but Java only does signed. The easiest way to work around this is to either not import the frequencyHz variable from their JSON reply or make it a long integer. I chose the later since the extra data might be useful down the road even though we don't use it now.
=> Schedules Direct EPG grabber failed to finish updating some satellite-based lineups

CHANGELOG.md, native/dll/DShowCapture-2/DeviceDiscovery.cpp, native/dll/DShowCapture-2/DeviceVerify.cpp, native/dll/DShowCapture-2/GraphManager.cpp
Each TS capture device now correctly only displays the tuners available on that capture device.   Analog capture still needs work
=> Fix for Hauppauge 885 tuners with Alt TS Capture Devices (Windows)

CHANGELOG.md, native/ax/MpegDeMux-3/CDemuxer.cpp, native/ax/MpegDeMux-3/CDemuxer.h
This fixes an issue in MpegDeMux.ax
When storing the MPEG2 sequence header into bottom of the MPEG2VIDEOINFO data structure it is defined as an array of type DWORD.  Since the MPEG2 sequence headers are by nature 22, 86 or 150 bytes they are not naturally DWORD aligned.  Some MPEG2 files crash when the downstream filter is trying to connect with these native header sizes.  Padding the header and most critically the cbSequenceHeader member to a modulo 4 value corrects this.
The forum issue is:  https://forums.sagetv.com/forums/showthread.php?t=66336
MPEG2VIDEOINFO  definiton: https://docs.microsoft.com/en-us/previous-versions/ms787321(v%3Dvs.85)
The crash was reproduced on my system and the fix confirmed.
=> Fix MpegDeMux DWORD alignment causing playback crash

CHANGELOG.md, java/sage/Version.java, java/sage/media/format/FormatParser.java
There was an inadvertent consequence to adding a format substitution from "MATROSKA,WEBM" -> "MATROSKA".  This caused conversions to MKV container to break.
For more info see https://forums.sagetv.com/forums/showthread.php?t=66492
=> Fix conversion to MKV

CHANGELOG.md, java/sage/FFMPEGTranscoder.java, java/sage/MiniPlayer.java, java/sage/Version.java
I made some minor changes to the behavior of how SageTV determines when to use fixed transcoding.  I added a number of properties to the fixed transcode section to allow for HD transcoding.  I tried my best to make the changes backwards compatible.  I do not believe they will interfere with any of the other clients.  There are a few users using this, and it appears to be working well.
Josh
=> Transcoding enhancements no debug

java/sage/MiniPlayer.java, java/sage/Seeker.java, java/sage/VideoFrame.java
It appears that when SageTV is doing server side transcoding that it is not able to do a fastmuxswitch and have the client transition to the new program/timeslot.  I have noticed this behavior in the Placeshifter, and the andriod client.  With this change, placeshifter is able to transition between timeslots without issue.  And when you are using a client without transcoding, it does a fastmuxswitch without issue.
=> This will disable FastMuxSwitch if a client is actively transcoding a liveTV stream.

CHANGELOG.md, java/sage/FFMPEGTranscoder.java
This is the first of a few changes to allow for remuxing when the container format is not supported using the miniclient.  I am going to add a property for a fixed remux format.
Let me know if you have any questions or concerns.  High level testing has looked good.  Submitting in smaller pieces.
=> Added option to FFMpegTranscoder to be able to copy audio or video without conversion (remux)

java/sage/MiniClientSageRenderer.java, java/sage/MiniPlayer.java
Modified the Minicliet to have a setting for fixed remuxing when the video codec and audio codec are both supported, but the container is not.  This allows for lower cost transcoding in certain situations, and can also be used to fix files which may have issues with their containers.
=> Modified the Minicliet to have a setting for fixed remuxing

CHANGELOG.md
Updated the STV to use an updated version of the GoogleWeather.jar file (3.x).  It will still work with or without that jar as with previous STVs.  The new GoogleWeather plugin is completed and will be pushed soon as well.
=> Weather updated in STV to now use OpenWeatherMap

installer/wix/SageTVSetup/SageTVVersionInclude.wxi, native/ax/Channel-2/Channel.h, native/include/version.h
bool, true and false are not part of WIN32 natively.  This reverts https://github.com/google/sagetv/pull/461 but only for Windows compiling.
=> Revert PR#461 for Windows build

CHANGELOG.md, installer/wix/SageTVSetup/Product.wxs, native/SageWorkspace.sln, native/dll/TunerStub/DirectTVTuner.vcxproj, native/dll/TunerStub/TunerStubDLL.cpp
Adding a tuning DLL for DirecTV http tuning.  Confirmed working by a user here:  https://forums.sagetv.com/forums/showthread.php?p=631452&postcount=3  The 32-bit or 64-bit version will be included in the appropriate Windows installers for the next release.
=> Add DirecTVtuner DLL for http tuning.

.github/workflows/ci.yml, .travis.yml.old, CHANGELOG.md, java/sage/Version.java
As the ubuntu 20.04 build forces glibc to be 2.28 the linux SageTV build would not run on Ubuntu 18.04 which is still under support until mid 2023.  Given that 18.04 may still be used by users for awhile I updated the build process to use Ubuntu 18.04 which allows SageTV build to run on either 18.04 and 20.04 (and their equivalents) .
I also renamed the travis.yml so it would quit running and failing on forked repos
=> Update build process to support ubuntu 18.04 as it is still under support [ci release]

CHANGELOG.md, java/sage/EPG.java, java/sage/SageConstants.java, java/sage/Version.java, java/sage/epg/sd/SDRipper.java, java/sage/epg/sd/SDSageSession.java, java/sage/epg/sd/SDUtils.java
These are a few leftover issues discovered after more users migrated to the latest release.
=> SDEPG Changes to further resolve token and login issues with SD

.github/workflows/ci.yml
There's an incompatibility with the older cache version action which the setup-java one depends on. I'm also updating the checkout version as well for good measure.
=> Update actions for new cache version

CHANGELOG.md, java/sage/Version.java, java/sage/miniclient/DirectX9GFXCMD.java, java/sage/miniclient/MiniClient.java
Buffer clear fix which was failing on windows placeshifter due to jdk changes
=> Placeshifter fix for windows
